name: BukkitJS
version: '${version}'
main: com.gmail.necnionch.myplugin.bukkitjs.bukkit.BukkitJSPlugin
api-version: 1.17
authors: [ Necnion8 ]


commands:
  bjs:
    permission: bukkitjavascript.command.default-op

permissions:
  bukkitjavascript.command.bukkitjavascript:
    default: false
  bukkitjavascript.default-op:
    default: op
